// User actions
export const SET_USER = 'SET_USER';

// Category actions
export const SET_CATEGORIES = 'SET_CATEGORIES';
export const ADD_CATEGORY = 'ADD_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';

// Notification actions
export const SET_SUCCESS_NOTIFICATION = 'SET_SUCCESS_NOTIFICATION';
export const SET_ERROR_NOTIFICATION = 'SET_ERROR_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';